#PlayerStats v1.0
#Developed by Frogsoup (Parker).

## Database Information ##
address: 'localhost'
username: 'root'
password: ''
database: 'player_stats'

#Please pay attention to the syntax, or format, of the options
# below. If you enter an option that is not there it will not
# work. Options are case-sensitive so be careful!

## Time Format ##
#Choose how the time online should be displayed.
#Avaliable Options: seconds, minutes, hours, days, weeks, months, or years.
time-format: 'days'

## Date Format ##
#Choose how all dates should be displayed.
#Avaliable Options: MM-dd-yyyy, dd-MM-yyyy, yyyy-MM-dd
date-format: 'dd-MM-yyyy'

#End of config.yml.
